package com.lockbox.model.enums;

public enum ActionType {
    // Authentication actions
    USER_LOGIN, USER_LOGOUT, USER_REGISTRATION, PASSWORD_RESET_REQUEST, PASSWORD_RESET_COMPLETE, PASSWORD_CHANGE,
    MFA_SETUP, MFA_VERIFICATION, LOGIN_FAILED, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, AUTHENTICATION, LOGIN_NEW_DEVICE,

    // TOTP actions
    TOTP_SETUP_INITIATED, TOTP_SETUP_VERIFICATION, TOTP_SETUP_COMPLETED, TOTP_VERIFICATION, TOTP_VERIFICATION_SUCCESS,
    TOTP_DISABLED, TOTP_OPERATION_VERIFICATION,

    // Vault actions
    VAULT_CREATE, VAULT_VIEW, VAULT_UPDATE, VAULT_DELETE, VAULT_SHARE, VAULT_UNSHARE,

    // Credential actions
    CREDENTIAL_CREATE, CREDENTIAL_VIEW, CREDENTIAL_UPDATE, CREDENTIAL_DELETE, CREDENTIAL_PASSWORD_VIEW,
    CREDENTIAL_EXPORT, CREDENTIAL_IMPORT, CREDENTIAL_VERIFY,

    // Domain actions
    DOMAIN_CREATE, DOMAIN_VIEW, DOMAIN_UPDATE, DOMAIN_DELETE,

    // Admin actions
    ADMIN_USER_MANAGE, ADMIN_AUDIT_LOG_CLEANUP, ADMIN_SYSTEM_BACKUP, ADMIN_SYSTEM_RESTORE, ADMIN_SYSTEM_SETTINGS_UPDATE,
    ADMIN_BLOCKCHAIN_VERIFICATION, ADMIN_BLOCKCHAIN_UPDATE, ADMIN_BLOCKCHAIN_RECORD,

    // Security events
    ENCRYPTION_KEY_ROTATION, SUSPICIOUS_ACTIVITY_DETECTED, IP_ADDRESS_BLOCKED, API_RATE_LIMIT_EXCEEDED,
    SECURITY_WARNING, FREQUENT_PASSWORD_CHANGES,

    // Data management
    DATA_EXPORT, DATA_IMPORT, DATA_PURGE
}
