package com.lockbox.model;

public enum ActionType {
    // Authentication actions
    USER_LOGIN, USER_LOGOUT, USER_REGISTRATION, PASSWORD_RESET_REQUEST, PASSWORD_RESET_COMPLETE, PASSWORD_CHANGE,
    MFA_SETUP, MFA_VERIFICATION, LOGIN_FAILED, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,

    // Vault actions
    VAULT_CREATE, VAULT_VIEW, VAULT_UPDATE, VAULT_DELETE, VAULT_SHARE, VAULT_UNSHARE,

    // Credential actions
    CREDENTIAL_CREATE, CREDENTIAL_VIEW, CREDENTIAL_UPDATE, CREDENTIAL_DELETE, CREDENTIAL_PASSWORD_VIEW,
    CREDENTIAL_EXPORT, CREDENTIAL_IMPORT,

    // Domain actions
    DOMAIN_CREATE, DOMAIN_VIEW, DOMAIN_UPDATE, DOMAIN_DELETE,

    // Admin actions
    ADMIN_USER_MANAGE, ADMIN_AUDIT_LOG_CLEANUP, ADMIN_SYSTEM_BACKUP, ADMIN_SYSTEM_RESTORE, ADMIN_SYSTEM_SETTINGS_UPDATE,

    // Security events
    ENCRYPTION_KEY_ROTATION, SUSPICIOUS_ACTIVITY_DETECTED, IP_ADDRESS_BLOCKED, API_RATE_LIMIT_EXCEEDED,

    // Data management
    DATA_EXPORT, DATA_IMPORT, DATA_PURGE
}
